### Data Exploration to afinity datasets

Datasets: 
1. ChEMBL 
2. PDSP
3. BindingDB

##### **0° INTRO**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:

BASE_DIR = Path.cwd().parent

DATA_DIR = BASE_DIR /  Path("data/raw")

DATA_CHEMBL = DATA_DIR / "chembl" / "chembl214_ki_ic50.parquet"

BINDINGDB_DIR = DATA_DIR / "BINDINGDB" / "BindingDB_BindingDB_Articles.tsv"
PDSP_DIR = DATA_DIR / "PDSP" / "BindingDB_PDSPKi.tsv"

#### **1° Afinity Datasets**

##### **Data by ChEMBL**

In [3]:
# TODO: Explorar los conjuntos de datos de afinidad y actividad biológica para identificar patrones, correlaciones y posibles relaciones entre las características moleculares y la afinidad hacia el receptor 5HT1A.

data_chembl = pd.read_parquet(DATA_CHEMBL)
data_summary = pd.DataFrame({
    'Columns': data_chembl.columns,
    'Data types': data_chembl.dtypes,
    'Missing values': data_chembl.isnull().sum(),
    'null%': data_chembl.isnull().mean() * 100,
    # 'unique values': data_chembl.nunique()
})

pd.set_option('display.max_rows', None)
display(data_summary)

,Columns,Data types,Missing values,null%
action_type,action_type,object,7132,91.283758
activity_comment,activity_comment,str,6760,86.522463
activity_id,activity_id,int64,0,0.000000
activity_properties,activity_properties,object,0,0.000000
assay_chembl_id,assay_chembl_id,str,0,0.000000
assay_description,assay_description,str,0,0.000000
assay_type,assay_type,str,0,0.000000
assay_variant_accession,assay_variant_accession,object,7813,100.000000
assay_variant_mutation,assay_variant_mutation,object,7813,100.000000
bao_endpoint,bao_endpoint,str,0,0.000000
bao_format,bao_format,str,0,0.000000
bao_label,bao_label,str,0,0.000000
canonical_smiles,canonical_smiles,str,7,0.089594
data_validity_comment,data_validity_comment,str,7760,99.321643
data_validity_description,data_validity_description,str,7760,99.321643
document_chembl_id,document_chembl_id,str,0,0.000000
document_journal,document_journal,str,913,11.685652
document_year,document_year,int64,0,0.000000
ligand_efficiency,ligand_efficiency,object,1372,17.560476
modality,modality,float64,7813,100.000000
molecule_chembl_id,molecule_chembl_id,str,0,0.000000
molecule_pref_name,molecule_pref_name,str,7262,92.947651
parent_molecule_chembl_id,parent_molecule_chembl_id,str,0,0.000000
pchembl_value,pchembl_value,str,934,11.954435
potential_duplicate,potential_duplicate,int64,0,0.000000
qudt_units,qudt_units,str,216,2.764623
record_id,record_id,int64,0,0.000000
relation,relation,str,243,3.110201
src_id,src_id,int64,0,0.000000
standard_flag,standard_flag,int64,0,0.000000
standard_relation,standard_relation,str,243,3.110201
standard_text_value,standard_text_value,str,7778,99.552029
standard_type,standard_type,str,0,0.000000
standard_units,standard_units,str,216,2.764623
standard_upper_value,standard_upper_value,object,7813,100.000000
standard_value,standard_value,str,243,3.110201
target_chembl_id,target_chembl_id,str,0,0.000000
target_organism,target_organism,str,0,0.000000
target_pref_name,target_pref_name,str,0,0.000000
target_tax_id,target_tax_id,str,0,0.000000
text_value,text_value,str,7778,99.552029
toid,toid,object,7813,100.000000
type,type,str,0,0.000000
units,units,str,1602,20.504288
uo_units,uo_units,str,216,2.764623
upper_value,upper_value,object,7813,100.000000
value,value,str,243,3.110201

In [20]:

# ? What is the observational unit of the data?

print(data_chembl[['assay_type', 'type', 'units', 'assay_description']])

     assay_type       type        units  \
0             B         Ki           nM
1             B         Ki           nM
2             B         Ki           nM
3             B         Ki           nM
4             B         Ki           nM
5             B         Ki           nM
6             B         Ki           nM
7             B         Ki           nM
8             B     Log Ki          NaN
9             B     Log Ki          NaN
10            B         Ki           nM
11            B         Ki           nM
12            B         Ki           nM
13            B         Ki           nM
14            B     Log Ki          NaN
15            B         Ki           nM
16            B         Ki           nM
17            B         Ki           nM
18            B      pIC50          NaN
19            B      pIC50          NaN
20            B      pIC50          NaN
21            B      pIC50          NaN
22            B      pIC50          NaN
23            B      pIC50          NaN
24            B      pIC50          NaN
25            B      pIC50          NaN
26            B      pIC50          NaN
27            B      pIC50          NaN
28            B      pIC50          NaN
29            B      pIC50          NaN
30            B      pIC50          NaN
31            B      pIC50          NaN
32            B      pIC50          NaN
33            B      pIC50          NaN
34            B         Ki           nM
35            B      pIC50          NaN
36            B      pIC50          NaN
37            B      pIC50          NaN
38            B         Ki           nM
39            B         Ki           nM
40            B         Ki           nM
41            B         Ki           nM
42            B        pKi          NaN
43            B         Ki           nM
44            B         Ki           nM
45            B         Ki           nM
46            B         Ki           nM
47            B         Ki           nM
48            B         Ki           nM
49            B         Ki           nM
50            B         Ki           nM
51            B         Ki           nM
52            B         Ki           nM
53            B         Ki           nM
54            B         Ki           nM
55            B         Ki           nM
56            B         Ki           nM
57            B         Ki           nM
58            B         Ki           nM
59            B         Ki           nM
60            B         Ki           nM
61            B         Ki           nM
62            B         Ki           nM
63            B         Ki           nM
64            B         Ki           nM
65            B         Ki           nM
66            B         Ki           nM
67            B     Log Ki          NaN
68            B     Log Ki          NaN
69            B     Log Ki          NaN
70            B         Ki           nM
71            B     Log Ki          NaN
72            B         Ki           nM
73            B     Log Ki          NaN
74            B         Ki           nM
75            B     Log Ki          NaN
76            B         Ki           nM
77            B         Ki           nM
78            B         Ki           nM
79            B         Ki           nM
80            B         Ki           nM
81            B         Ki           nM
82            B         Ki           nM
83            B         Ki           nM
84            B         Ki           nM
85            B         Ki           nM
86            B         Ki           nM
87            B         Ki           nM
88            B         Ki           nM
89            B         Ki           nM
90            B         Ki           nM
91            B     Log Ki          NaN
92            B         Ki           nM
93            B         Ki           nM
94            B         Ki           nM
95            B         Ki           nM
96            B         Ki           nM
97            B         Ki           nM
98            B     Log Ki          NaN
99            B         Ki           nM
100           B         Ki           nM
101           B     Log Ki          NaN
102           B     Log Ki          NaN
103           B         Ki           nM
104           B     Log Ki          NaN
105           B         Ki           nM
106           B         Ki           nM
107           B         Ki           nM
108           B         Ki           nM
109           B         Ki           nM
110           B         Ki           nM
111           B         Ki           nM
112           B       IC50           nM
113           B         Ki           nM
114           B     Log Ki          NaN
115           B     Log Ki          NaN
116           B         Ki           nM
117           B     Log Ki          NaN
118           B         Ki           nM
119           B         Ki           nM
120           B         Ki           nM
121           B         Ki           nM
122           B     Log Ki          NaN
123           B     Log Ki          NaN
124           B         Ki           nM
125           B         Ki           nM
126           B         Ki           nM
127           B         Ki           nM
128           B         Ki           nM
129           B     Log Ki          NaN
130           B         Ki           nM
131           B     Log Ki          NaN
132           B         Ki           nM
133           B         Ki           nM
134           B         Ki           nM
135           B         Ki           nM
136           B         Ki           nM
137           B      pIC50          NaN
138           B         Ki           nM
139           B         Ki           nM
140           B      pIC50          NaN
141           B         Ki           nM
142           B   Log IC50          NaN
143           B      pIC50          NaN
144           B         Ki           nM
145           B      pIC50          NaN
146           B         Ki           nM
147           B         Ki           nM
148           B         Ki           nM
149           B         Ki           nM
150           B         Ki           nM
151           B      pIC50          NaN
152           B         Ki           nM
153           B         Ki           nM
154           B         Ki           nM
155           B      pIC50          NaN
156           B      pIC50          NaN
157           B      pIC50          NaN
158           B         Ki           nM
159           B      pIC50          NaN
160           B         Ki           nM
161           B         Ki           nM
162           B   Log IC50          NaN
163           B   Log IC50          NaN
164           B         Ki           nM
165           B         Ki           nM
166           B         Ki           nM
167           B         Ki           nM
168           B      pIC50          NaN
169           B         Ki           nM
170           B         Ki           nM
171           B         Ki           nM
172           B      pIC50          NaN
173           B         Ki           nM
174           B         Ki           nM
175           B         Ki           nM
176           B         Ki           nM
177           B      pIC50          NaN
178           B      pIC50          NaN
179           B         Ki           nM
180           B         Ki           nM
181           B         Ki           nM
182           B   Log IC50          NaN
183           B         Ki           nM
184           B         Ki           nM
185           B         Ki           nM
186           B         Ki           nM
187           B         Ki           nM
188           B         Ki           nM
189           B      pIC50          NaN
190           B      pIC50          NaN
191           B      pIC50          NaN
192           B   Log IC50          NaN
193           B      pIC50          NaN
194           B         Ki           nM
195           B         Ki           nM
196           B         Ki           nM
197           B         Ki           nM
198           B         Ki           nM
199           B     Log Ki          NaN
200           B         Ki           nM
201           F         Ki           nM
202           B     Log Ki          NaN
203           B         Ki           nM
204           B         Ki           nM
205           B         Ki           nM
206           F         Ki           nM
207           B         Ki           nM
208           F         Ki           nM
209           B         Ki           nM
210           B         Ki           nM
211           B         Ki           nM
212           B         Ki           nM
213           F         Ki           nM
214           B         Ki           nM
215           F         Ki           nM
216           B         Ki           nM
217           B         Ki           nM
218           B         Ki           nM
219           B         Ki           nM
220           B         Ki           nM
221           B         Ki           nM
222           B     Log Ki          NaN
223           B         Ki           nM
224           B         Ki           nM
225           B         Ki           nM
226           B         Ki           nM
227           B         Ki           nM
228           F         Ki           nM
229           B         Ki           nM
230           B         Ki           nM
231           B         Ki           nM
232           B         Ki           nM
233           B         Ki           nM
234           B         Ki           nM
235           B     Log Ki          NaN
236           B         Ki           nM
237           B         Ki           nM
238           B         Ki           nM
239           F         Ki           nM
240           B         Ki           nM
241           B         Ki           nM
242           B         Ki           nM
243           B         Ki           nM
244           B         Ki           nM
245           B         Ki           nM
246           B         Ki           nM
247           B         Ki           nM
248           F         Ki           nM
249           B         Ki           nM
250           B         Ki           nM
251           B         Ki           nM
252           B         Ki           nM
253           B         Ki           nM
254           F         Ki           nM
255           B         Ki           nM
256           B         Ki           nM
257           B         Ki           nM
258           B         Ki           nM
259           B         Ki           nM
260           B         Ki           nM
261           F         Ki           nM
262           B         Ki           nM
263           F         Ki           nM
264           B         Ki           nM
265           B         Ki           nM
266           B         Ki           nM
267           B         Ki           nM
268           B         Ki           nM
269           B         Ki           nM
270           B         Ki           nM
271           F         Ki           nM
272           B         Ki           nM
273           F         Ki           nM
274           B         Ki           nM
275           B         Ki           nM
276           B         Ki           nM
277           B         Ki           nM
278           B     Log Ki          NaN
279           B         Ki           nM
280           F         Ki           nM
281           B         Ki           nM
282           F         Ki           nM
283           B         Ki           nM
284           F         Ki           nM
285           B         Ki           nM
286           B         Ki           nM
287           B         Ki           nM
288           B         Ki           nM
289           B         Ki           nM
290           B         Ki           nM
291           B         Ki           nM
292           B         Ki           nM
293           B         Ki           nM
294           B         Ki           nM
295           B         Ki           nM
296           B         Ki           nM
297           B         Ki           nM
298           B         Ki           nM
299           B         Ki           nM
300           B         Ki           nM
301           B         Ki           nM
302           B         Ki           nM
303           B         Ki           nM
304           B         Ki           nM
305           B         Ki           nM
306           B         Ki           nM
307           B         Ki           nM
308           B         Ki           nM
309           B         Ki           nM
310           B         Ki           nM
311           B         Ki           nM
312           F         Ki           nM
313           B         Ki           nM
314           B         Ki           nM
315           B         Ki           nM
316           B         Ki           nM
317           B         Ki           nM
318           B         Ki           nM
319           B         Ki           nM
320           F         Ki           nM
321           B         Ki           nM
322           B         Ki           nM
323           B         Ki           nM
324           B         Ki           nM
325           F         Ki           nM
326           B         Ki           nM
327           B         Ki           nM
328           F         Ki           nM
329           B         Ki           nM
330           B         Ki           nM
331           B         Ki           nM
332           B         Ki           nM
333           B         Ki           nM
334           B         Ki           nM
335           B         Ki           nM
336           B         Ki           nM
337           F         Ki           nM
338           B         Ki           nM
339           F         Ki           nM
340           B         Ki           nM
341           B         Ki           nM
342           B         Ki           nM
343           B         Ki           nM
344           B         Ki           nM
345           F         Ki           nM
346           B         Ki           nM
347           B         Ki           nM
348           B         Ki           nM
349           B         Ki           nM
350           B         Ki           nM
351           B         Ki           nM
352           B         Ki           nM
353           B         Ki           nM
354           B         Ki           nM
355           B         Ki           nM
356           F         Ki           nM
357           B         Ki           nM
358           B         Ki           nM
359           B         Ki           nM
360           B         Ki           nM
361           B         Ki           nM
362           B         Ki           nM
363           F       IC50           nM
364           F       IC50           nM
365           B         Ki           nM
366           B         Ki           nM
367           B         Ki           nM
368           B         Ki           nM
369           B         Ki           nM
370           B         Ki           nM
371           B         Ki           nM
372           B         Ki           nM
373           B         Ki           nM
374           F       IC50           nM
375           F       IC50           nM
376           B         Ki           nM
377           F       IC50           nM
378           F       IC50           nM
379           B         Ki           nM
380           B         Ki           nM
381           B         Ki           nM
382           F       IC50           nM
383           B         Ki           nM
384           B         Ki           nM
385           B         Ki           nM
386           B         Ki           nM
387           F       IC50           nM
388           F       IC50           nM
389           B         Ki           nM
390           B         Ki           nM
391           B         Ki           nM
392           B         Ki           nM
393           B         Ki           nM
394           B         Ki           nM
395           B         Ki           nM
396           B         Ki           nM
397           F       IC50           nM
398           B         Ki           nM
399           F       IC50           nM
400           F       IC50           nM
401           B         Ki           nM
402           B         Ki           nM
403           B         Ki           nM
404           B         Ki           nM
405           F       IC50           nM
406           F       IC50           nM
407           B         Ki           nM
408           B         Ki           nM
409           B         Ki           nM
410           B         Ki           nM
411           B         Ki           nM
412           B         Ki           nM
413           B         Ki           nM
414           B         Ki           nM
415           B         Ki           nM
416           F       IC50           nM
417           F       IC50           nM
418           B         Ki           nM
419           B         Ki           nM
420           B         Ki           nM
421           B         Ki           nM
422           B         Ki           nM
423           B         Ki           nM
424           B         Ki           nM
425           B         Ki           nM
426           B         Ki           nM
427           B         Ki           nM
428           B         Ki           nM
429           B         Ki           nM
430           B         Ki           nM
431           B         Ki           nM
432           B         Ki           nM
433           B         Ki           nM
434           B         Ki           nM
435           B         Ki           nM
436           B         Ki           nM
437           B         Ki           nM
438           F       IC50           nM
439           F       IC50           nM
440           B         Ki           nM
441           F       IC50           nM
442           F       IC50           nM
443           B         Ki           nM
444           B         Ki           nM
445           B         Ki           nM
446           B         Ki           nM
447           B         Ki           nM
448           B         Ki           nM
449           B         Ki           nM
450           B         Ki           nM
451           B         Ki           nM
452           B         Ki           nM
453           B         Ki           nM
454           B         Ki           nM
455           B      pIC50          NaN
456           B      pIC50          NaN
457           B      pIC50          NaN
458           B      pIC50          NaN
459           B      pIC50          NaN
460           B         Ki           nM
461           B      pIC50          NaN
462           B      pIC50          NaN
463           B      pIC50          NaN
464           B         Ki           nM
465           B      pIC50          NaN
466           B         Ki           nM
467           B      pIC50          NaN
468           B      pIC50          NaN
469           B         Ki           nM
470           B         Ki           nM
471           B         Ki           nM
472           B         Ki           nM
473           B      pIC50          NaN
474           B         Ki           nM
475           B      pIC50          NaN
476           B      pIC50          NaN
477           B      pIC50          NaN
478           B      pIC50          NaN
479           B      pIC50          NaN
480           B      pIC50          NaN
481           B      pIC50          NaN
482           B         Ki           nM
483           B      pIC50          NaN
484           B      pIC50          NaN
485           B      pIC50          NaN
486           B      pIC50          NaN
487           B      pIC50          NaN
488           B      pIC50          NaN
489           B      pIC50          NaN
490           B      pIC50          NaN
491           B         Ki           nM
492           B         Ki           nM
493           B      pIC50          NaN
494           B      pIC50          NaN
495           B         Ki           nM
496           B         Ki           nM
497           B         Ki           nM

In [5]:

# ? Ki or IC50? Which one is more relevant for our analysis?

print(data_chembl["type"].value_counts().T)
print(data_chembl["standard_type"].value_counts().T)
print(data_chembl["standard_relation"].value_counts().T)
print(data_chembl["standard_units"].value_counts().T)

type
Ki           5770
pKi           950
IC50          654
Log Ki        248
pIC50          86
-Log IC50      83
Log IC50       19
Ki(app)         3
Name: count, dtype: int64
standard_type
Ki      6971
IC50     842
Name: count, dtype: int64
standard_relation
=     6933
>      568
<       68
>=       1
Name: count, dtype: int64
standard_units
nM    7584
%       13
Name: count, dtype: int64

In [6]:

# ? Which molecules have unique SMILES representations? Are there any duplicates or inconsistencies in the SMILES strings?

print(data_chembl["canonical_smiles"].nunique())
print(data_chembl["canonical_smiles"].duplicated().sum())
print(data_chembl["pchembl_value"].describe())

6094
1718
count     6879
unique     575
top       8.40
freq        62
Name: pchembl_value, dtype: object

In [7]:
# TODO: Create groups based on unique SMILES representations and visualize the distribution of pChEMBL values for each group. This will help identify any patterns or trends in the data that may be relevant to our analysis of the 5HT1A receptor.


molecule_groups = data_chembl.groupby(['canonical_smiles', 'molecule_chembl_id']).size()
molecule_groups = molecule_groups.reset_index(name='count')
molecules_with_duplicates = molecule_groups[molecule_groups['count'] > 1]
print(f"Molecules with duplicate SMILES representations: {molecules_with_duplicates.shape[0]}")

Molecules with duplicate SMILES representations: 1139

In [8]:
def molecule_unique_smiles(molecules):
    df = molecules[('molecule_chembl_id', 'count')]

##### **Data by BidingDB**

In [9]:
data_bindb = pd.read_csv(BINDINGDB_DIR, sep='\t')
data_bindb.info()

C:\Users\alexl\AppData\Local\Temp\ipykernel_12564\1711188053.py:1: DtypeWarning: Columns (0: Ki (nM), 1: IC50 (nM), 2: Kd (nM), 3: EC50 (nM), 4: koff (s-1), 5: Temp (C), 6: Article DOI, 7: ChEMBL ID of Ligand, 8: DrugBank ID of Ligand, 9: KEGG ID of Ligand, 10: ZINC ID of Ligand, 11: UniProt (SwissProt) Secondary ID(s) of Target Chain 1, 12: UniProt (TrEMBL) Submitted Name of Target Chain 1, 13: UniProt (TrEMBL) Entry Name of Target Chain 1, 14: UniProt (TrEMBL) Primary ID of Target Chain 1, 15: UniProt (TrEMBL) Secondary ID(s) of Target Chain 1, 16: BindingDB Target Chain Sequence 2, 17: PDB ID(s) of Target Chain 2, 18: UniProt (SwissProt) Recommended Name of Target Chain 2, 19: UniProt (SwissProt) Entry Name of Target Chain 2, 20: UniProt (SwissProt) Primary ID of Target Chain 2, 21: UniProt (SwissProt) Secondary ID(s) of Target Chain 2, 22: UniProt (TrEMBL) Submitted Name of Target Chain 2, 23: UniProt (TrEMBL) Entry Name of Target Chain 2, 24: UniProt (TrEMBL) Primary ID of Target Chain 2, 25: BindingDB Target Chain Sequence 3, 26: PDB ID(s) of Target Chain 3, 27: UniProt (SwissProt) Recommended Name of Target Chain 3, 28: UniProt (SwissProt) Entry Name of Target Chain 3, 29: UniProt (SwissProt) Primary ID of Target Chain 3, 30: UniProt (SwissProt) Secondary ID(s) of Target Chain 3, 31: UniProt (TrEMBL) Submitted Name of Target Chain 3, 32: UniProt (TrEMBL) Entry Name of Target Chain 3, 33: UniProt (TrEMBL) Primary ID of Target Chain 3, 34: UniProt (TrEMBL) Secondary ID(s) of Target Chain 3, 35: BindingDB Target Chain Sequence 4, 36: PDB ID(s) of Target Chain 4, 37: UniProt (SwissProt) Recommended Name of Target Chain 4, 38: UniProt (SwissProt) Entry Name of Target Chain 4, 39: UniProt (SwissProt) Primary ID of Target Chain 4, 40: UniProt (SwissProt) Secondary ID(s) of Target Chain 4, 41: BindingDB Target Chain Sequence 5, 42: PDB ID(s) of Target Chain 5, 43: UniProt (SwissProt) Recommended Name of Target Chain 5, 44: UniProt (SwissProt) Entry Name of Target Chain 5, 45: UniProt (SwissProt) Primary ID of Target Chain 5, 46: UniProt (SwissProt) Secondary ID(s) of Target Chain 5, 47: BindingDB Target Chain Sequence 6, 48: PDB ID(s) of Target Chain 6, 49: UniProt (SwissProt) Recommended Name of Target Chain 6, 50: UniProt (SwissProt) Entry Name of Target Chain 6, 51: UniProt (SwissProt) Primary ID of Target Chain 6, 52: UniProt (SwissProt) Secondary ID(s) of Target Chain 6, 53: BindingDB Target Chain Sequence 7, 54: UniProt (SwissProt) Recommended Name of Target Chain 7, 55: UniProt (SwissProt) Entry Name of Target Chain 7, 56: UniProt (SwissProt) Primary ID of Target Chain 7, 57: UniProt (SwissProt) Secondary ID(s) of Target Chain 7, 58: BindingDB Target Chain Sequence 8, 59: PDB ID(s) of Target Chain 8, 60: UniProt (SwissProt) Recommended Name of Target Chain 8, 61: UniProt (SwissProt) Entry Name of Target Chain 8, 62: UniProt (SwissProt) Primary ID of Target Chain 8, 63: UniProt (SwissProt) Secondary ID(s) of Target Chain 8, 64: BindingDB Target Chain Sequence 9, 65: UniProt (SwissProt) Recommended Name of Target Chain 9, 66: UniProt (SwissProt) Entry Name of Target Chain 9, 67: UniProt (SwissProt) Primary ID of Target Chain 9, 68: UniProt (SwissProt) Secondary ID(s) of Target Chain 9, 69: BindingDB Target Chain Sequence 10, 70: UniProt (SwissProt) Recommended Name of Target Chain 10, 71: UniProt (SwissProt) Entry Name of Target Chain 10, 72: UniProt (SwissProt) Primary ID of Target Chain 10, 73: UniProt (SwissProt) Secondary ID(s) of Target Chain 10, 74: BindingDB Target Chain Sequence 11, 75: PDB ID(s) of Target Chain 11, 76: UniProt (SwissProt) Recommended Name of Target Chain 11, 77: UniProt (SwissProt) Entry Name of Target Chain 11, 78: UniProt (SwissProt) Primary ID of Target Chain 11, 79: UniProt (SwissProt) Secondary ID(s) of Target Chain 11) have mixed types. Specify dtype option on import or set low_memory=False.
  data_bindb = pd.read_csv(BINDINGDB_DIR, sep='\t')

<class 'pandas.DataFrame'>
RangeIndex: 93712 entries, 0 to 93711
Columns: 640 entries, BindingDB Reactant_set_id to UniProt (TrEMBL) Alternative ID(s) of Target Chain 50
dtypes: float64(534), int64(3), object(5), str(98)
memory usage: 708.2+ MB

In [10]:
data_summary = pd.DataFrame({
    'Columns': data_bindb.columns,
    'Data types': data_bindb.dtypes,
    'Missing values': data_bindb.isnull().sum(),
    'null%': data_bindb.isnull().mean() * 100,
    'unique values': data_bindb.nunique()
})

pd.set_option('display.max_rows', None)
display(data_summary)

,Columns,Data types,Missing values,null%,unique values
BindingDB Reactant_set_id,BindingDB Reactant_set_id,int64,0,0.000000,93522
Ligand SMILES,Ligand SMILES,str,57,0.060825,47940
Ligand InChI,Ligand InChI,str,51,0.054422,46304
Ligand InChI Key,Ligand InChI Key,str,51,0.054422,46304
BindingDB MonomerID,BindingDB MonomerID,int64,0,0.000000,47957
BindingDB Ligand Name,BindingDB Ligand Name,str,0,0.000000,48085
Target Name,Target Name,str,0,0.000000,2034
Target Source Organism According to Curator or DataSource,Target Source Organism According to Curator or...,str,45,0.048019,297
Ki (nM),Ki (nM),object,67922,72.479512,5937
IC50 (nM),IC50 (nM),object,30187,32.212523,10853
Kd (nM),Kd (nM),object,91062,97.172187,1646
EC50 (nM),EC50 (nM),object,89482,95.486170,1599
kon (M-1-s-1),kon (M-1-s-1),float64,93697,99.983994,15
koff (s-1),koff (s-1),object,93683,99.969054,22
pH,pH,float64,51907,55.389918,66
Temp (C),Temp (C),str,52410,55.926669,50
Curation/DataSource,Curation/DataSource,str,0,0.000000,3
Article DOI,Article DOI,str,5168,5.514769,2657
BindingDB Entry DOI,BindingDB Entry DOI,str,0,0.000000,2697
PMID,PMID,float64,3635,3.878906,2652
PubChem AID,PubChem AID,str,776,0.828069,3345
Patent Number,Patent Number,float64,93712,100.000000,0
Authors,Authors,str,55,0.058690,2685
Date of publication,Date of publication,str,0,0.000000,1189
Date in BindingDB,Date in BindingDB,str,0,0.000000,871
Institution,Institution,str,55,0.058690,1071
Link to Ligand in BindingDB,Link to Ligand in BindingDB,str,0,0.000000,47957
Link to Target in BindingDB,Link to Target in BindingDB,str,0,0.000000,2931
Link to Ligand-Target Pair in BindingDB,Link to Ligand-Target Pair in BindingDB,str,0,0.000000,82169
Ligand HET ID in PDB,Ligand HET ID in PDB,str,86062,91.836691,1911
PDB ID(s) for Ligand-Target Complex,PDB ID(s) for Ligand-Target Complex,str,86957,92.791745,1820
PubChem CID,PubChem CID,float64,194,0.207017,47688
PubChem SID,PubChem SID,float64,184,0.196346,47845
ChEBI ID of Ligand,ChEBI ID of Ligand,float64,93462,99.733225,63
ChEMBL ID of Ligand,ChEMBL ID of Ligand,str,80222,85.604832,4105
DrugBank ID of Ligand,DrugBank ID of Ligand,str,88126,94.039184,1160
IUPHAR_GRAC ID of Ligand,IUPHAR_GRAC ID of Ligand,float64,93604,99.884753,27
KEGG ID of Ligand,KEGG ID of Ligand,str,87400,93.264470,830
ZINC ID of Ligand,ZINC ID of Ligand,str,91243,97.365332,1348
Number of Protein Chains in Target (>1 implies a multichain complex),Number of Protein Chains in Target (>1 implies...,int64,0,0.000000,6
BindingDB Target Chain Sequence 1,BindingDB Target Chain Sequence 1,str,0,0.000000,2295
PDB ID(s) of Target Chain 1,PDB ID(s) of Target Chain 1,str,10922,11.654857,2136
UniProt (SwissProt) Recommended Name of Target Chain 1,UniProt (SwissProt) Recommended Name of Target...,str,3939,4.203304,1175
UniProt (SwissProt) Entry Name of Target Chain 1,UniProt (SwissProt) Entry Name of Target Chain 1,str,3939,4.203304,1518
UniProt (SwissProt) Primary ID of Target Chain 1,UniProt (SwissProt) Primary ID of Target Chain 1,str,3939,4.203304,1517
UniProt (SwissProt) Secondary ID(s) of Target Chain 1,UniProt (SwissProt) Secondary ID(s) of Target ...,str,21815,23.278769,1210
UniProt (SwissProt) Alternative ID(s) of Target Chain 1,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 1,UniProt (TrEMBL) Submitted Name of Target Chain 1,str,89252,95.240738,166
UniProt (TrEMBL) Entry Name of Target Chain 1,UniProt (TrEMBL) Entry Name of Target Chain 1,str,89252,95.240738,217
UniProt (TrEMBL) Primary ID of Target Chain 1,UniProt (TrEMBL) Primary ID of Target Chain 1,str,88542,94.483097,236
UniProt (TrEMBL) Secondary ID(s) of Target Chain 1,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,str,93053,99.296782,33
UniProt (TrEMBL) Alternative ID(s) of Target Chain 1,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 2,BindingDB Target Chain Sequence 2,str,85451,91.184694,157
PDB ID(s) of Target Chain 2,PDB ID(s) of Target Chain 2,str,86292,92.082124,168
UniProt (SwissProt) Recommended Name of Target Chain 2,UniProt (SwissProt) Recommended Name of Target...,str,85506,91.243384,93
UniProt (SwissProt) Entry Name of Target Chain 2,UniProt (SwissProt) Entry Name of Target Chain 2,str,85506,91.243384,111
UniProt (SwissProt) Primary ID of Target Chain 2,UniProt (SwissProt) Primary ID of Target Chain 2,str,85506,91.243384,111
UniProt (SwissProt) Secondary ID(s) of Target Chain 2,UniProt (SwissProt) Secondary ID(s) of Target ...,str,86159,91.940200,93
UniProt (SwissProt) Alternative ID(s) of Target Chain 2,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 2,UniProt (TrEMBL) Submitted Name of Target Chain 2,str,93460,99.731091,7
UniProt (TrEMBL) Entry Name of Target Chain 2,UniProt (TrEMBL) Entry Name of Target Chain 2,str,93460,99.731091,7
UniProt (TrEMBL) Primary ID of Target Chain 2,UniProt (TrEMBL) Primary ID of Target Chain 2,str,93442,99.711883,9
UniProt (TrEMBL) Secondary ID(s) of Target Chain 2,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 2,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 3,BindingDB Target Chain Sequence 3,str,93487,99.759903,44
PDB ID(s) of Target Chain 3,PDB ID(s) of Target Chain 3,str,93521,99.796184,24
UniProt (SwissProt) Recommended Name of Target Chain 3,UniProt (SwissProt) Recommended Name of Target...,str,93501,99.774842,20
UniProt (SwissProt) Entry Name of Target Chain 3,UniProt (SwissProt) Entry Name of Target Chain 3,str,93501,99.774842,19
UniProt (SwissProt) Primary ID of Target Chain 3,UniProt (SwissProt) Primary ID of Target Chain 3,str,93501,99.774842,19
UniProt (SwissProt) Secondary ID(s) of Target Chain 3,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93512,99.786580,18
UniProt (SwissProt) Alternative ID(s) of Target Chain 3,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 3,UniProt (TrEMBL) Submitted Name of Target Chain 3,str,93698,99.985061,2
UniProt (TrEMBL) Entry Name of Target Chain 3,UniProt (TrEMBL) Entry Name of Target Chain 3,str,93698,99.985061,2
UniProt (TrEMBL) Primary ID of Target Chain 3,UniProt (TrEMBL) Primary ID of Target Chain 3,str,93698,99.985061,2
UniProt (TrEMBL) Secondary ID(s) of Target Chain 3,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,str,93701,99.988262,1
UniProt (TrEMBL) Alternative ID(s) of Target Chain 3,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 4,BindingDB Target Chain Sequence 4,str,93654,99.938108,6
PDB ID(s) of Target Chain 4,PDB ID(s) of Target Chain 4,str,93703,99.990396,5
UniProt (SwissProt) Recommended Name of Target Chain 4,UniProt (SwissProt) Recommended Name of Target...,str,93654,99.938108,6
UniProt (SwissProt) Entry Name of Target Chain 4,UniProt (SwissProt) Entry Name of Target Chain 4,str,93654,99.938108,6
UniProt (SwissProt) Primary ID of Target Chain 4,UniProt (SwissProt) Primary ID of Target Chain 4,str,93654,99.938108,6
UniProt (SwissProt) Secondary ID(s) of Target Chain 4,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93654,99.938108,6
UniProt (SwissProt) Alternative ID(s) of Target Chain 4,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 4,UniProt (TrEMBL) Submitted Name of Target Chain 4,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 4,UniProt (TrEMBL) Entry Name of Target Chain 4,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 4,UniProt (TrEMBL) Primary ID of Target Chain 4,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 4,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 4,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 5,BindingDB Target Chain Sequence 5,str,93656,99.940242,4
PDB ID(s) of Target Chain 5,PDB ID(s) of Target Chain 5,str,93659,99.943444,4
UniProt (SwissProt) Recommended Name of Target Chain 5,UniProt (SwissProt) Recommended Name of Target...,str,93656,99.940242,4
UniProt (SwissProt) Entry Name of Target Chain 5,UniProt (SwissProt) Entry Name of Target Chain 5,str,93656,99.940242,4
UniProt (SwissProt) Primary ID of Target Chain 5,UniProt (SwissProt) Primary ID of Target Chain 5,str,93656,99.940242,4
UniProt (SwissProt) Secondary ID(s) of Target Chain 5,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93656,99.940242,4
UniProt (SwissProt) Alternative ID(s) of Target Chain 5,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 5,UniProt (TrEMBL) Submitted Name of Target Chain 5,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 5,UniProt (TrEMBL) Entry Name of Target Chain 5,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 5,UniProt (TrEMBL) Primary ID of Target Chain 5,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 5,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 5,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 6,BindingDB Target Chain Sequence 6,str,93709,99.996799,1
PDB ID(s) of Target Chain 6,PDB ID(s) of Target Chain 6,str,93709,99.996799,1
UniProt (SwissProt) Recommended Name of Target Chain 6,UniProt (SwissProt) Recommended Name of Target...,str,93709,99.996799,1
UniProt (SwissProt) Entry Name of Target Chain 6,UniProt (SwissProt) Entry Name of Target Chain 6,str,93709,99.996799,1
UniProt (SwissProt) Primary ID of Target Chain 6,UniProt (SwissProt) Primary ID of Target Chain 6,str,93709,99.996799,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 6,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93709,99.996799,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 6,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 6,UniProt (TrEMBL) Submitted Name of Target Chain 6,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 6,UniProt (TrEMBL) Entry Name of Target Chain 6,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 6,UniProt (TrEMBL) Primary ID of Target Chain 6,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 6,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 6,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 7,BindingDB Target Chain Sequence 7,str,93709,99.996799,1
PDB ID(s) of Target Chain 7,PDB ID(s) of Target Chain 7,float64,93712,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 7,UniProt (SwissProt) Recommended Name of Target...,str,93709,99.996799,1
UniProt (SwissProt) Entry Name of Target Chain 7,UniProt (SwissProt) Entry Name of Target Chain 7,str,93709,99.996799,1
UniProt (SwissProt) Primary ID of Target Chain 7,UniProt (SwissProt) Primary ID of Target Chain 7,str,93709,99.996799,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 7,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93709,99.996799,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 7,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 7,UniProt (TrEMBL) Submitted Name of Target Chain 7,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 7,UniProt (TrEMBL) Entry Name of Target Chain 7,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 7,UniProt (TrEMBL) Primary ID of Target Chain 7,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 7,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 7,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 8,BindingDB Target Chain Sequence 8,str,93709,99.996799,1
PDB ID(s) of Target Chain 8,PDB ID(s) of Target Chain 8,str,93709,99.996799,1
UniProt (SwissProt) Recommended Name of Target Chain 8,UniProt (SwissProt) Recommended Name of Target...,str,93709,99.996799,1
UniProt (SwissProt) Entry Name of Target Chain 8,UniProt (SwissProt) Entry Name of Target Chain 8,str,93709,99.996799,1
UniProt (SwissProt) Primary ID of Target Chain 8,UniProt (SwissProt) Primary ID of Target Chain 8,str,93709,99.996799,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 8,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93709,99.996799,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 8,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 8,UniProt (TrEMBL) Submitted Name of Target Chain 8,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 8,UniProt (TrEMBL) Entry Name of Target Chain 8,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 8,UniProt (TrEMBL) Primary ID of Target Chain 8,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 8,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 8,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 9,BindingDB Target Chain Sequence 9,str,93709,99.996799,1
PDB ID(s) of Target Chain 9,PDB ID(s) of Target Chain 9,float64,93712,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 9,UniProt (SwissProt) Recommended Name of Target...,str,93709,99.996799,1
UniProt (SwissProt) Entry Name of Target Chain 9,UniProt (SwissProt) Entry Name of Target Chain 9,str,93709,99.996799,1
UniProt (SwissProt) Primary ID of Target Chain 9,UniProt (SwissProt) Primary ID of Target Chain 9,str,93709,99.996799,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 9,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93709,99.996799,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 9,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 9,UniProt (TrEMBL) Submitted Name of Target Chain 9,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 9,UniProt (TrEMBL) Entry Name of Target Chain 9,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 9,UniProt (TrEMBL) Primary ID of Target Chain 9,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 9,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 9,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 10,BindingDB Target Chain Sequence 10,str,93709,99.996799,1
PDB ID(s) of Target Chain 10,PDB ID(s) of Target Chain 10,float64,93712,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 10,UniProt (SwissProt) Recommended Name of Target...,str,93709,99.996799,1
UniProt (SwissProt) Entry Name of Target Chain 10,UniProt (SwissProt) Entry Name of Target Chain 10,str,93709,99.996799,1
UniProt (SwissProt) Primary ID of Target Chain 10,UniProt (SwissProt) Primary ID of Target Chain 10,str,93709,99.996799,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 10,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93709,99.996799,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 10,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 10,UniProt (TrEMBL) Submitted Name of Target Chai...,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 10,UniProt (TrEMBL) Entry Name of Target Chain 10,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 10,UniProt (TrEMBL) Primary ID of Target Chain 10,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 10,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 10,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 11,BindingDB Target Chain Sequence 11,str,93709,99.996799,1
PDB ID(s) of Target Chain 11,PDB ID(s) of Target Chain 11,str,93709,99.996799,1
UniProt (SwissProt) Recommended Name of Target Chain 11,UniProt (SwissProt) Recommended Name of Target...,str,93709,99.996799,1
UniProt (SwissProt) Entry Name of Target Chain 11,UniProt (SwissProt) Entry Name of Target Chain 11,str,93709,99.996799,1
UniProt (SwissProt) Primary ID of Target Chain 11,UniProt (SwissProt) Primary ID of Target Chain 11,str,93709,99.996799,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 11,UniProt (SwissProt) Secondary ID(s) of Target ...,str,93709,99.996799,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 11,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 11,UniProt (TrEMBL) Submitted Name of Target Chai...,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 11,UniProt (TrEMBL) Entry Name of Target Chain 11,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 11,UniProt (TrEMBL) Primary ID of Target Chain 11,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 11,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 11,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 12,BindingDB Target Chain Sequence 12,float64,93712,100.000000,0
PDB ID(s) of Target Chain 12,PDB ID(s) of Target Chain 12,float64,93712,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 12,UniProt (SwissProt) Recommended Name of Target...,float64,93712,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 12,UniProt (SwissProt) Entry Name of Target Chain 12,float64,93712,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 12,UniProt (SwissProt) Primary ID of Target Chain 12,float64,93712,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 12,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,93712,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 12,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,93712,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 12,UniProt (TrEMBL) Submitted Name of Target Chai...,float64,93712,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 12,UniProt (TrEMBL) Entry Name of Target Chain 12,float64,93712,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 12,UniProt (TrEMBL) Primary ID of Target Chain 12,float64,93712,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 12,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,93712,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 12,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,93712,100.000000,0
BindingDB Target Chain Sequence 13,BindingDB Target Chain Sequence 13,float64,93712,100.000000,0
PDB ID(s) of Target Chain 13,PDB ID(s) of Target Chain 13,float64,93712,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 13,UniProt (SwissProt) Recommended Name of Target...,float64,93712,100.000000,0

##### **Data by PDSP**

In [11]:
data_pdsp = pd.read_csv(PDSP_DIR, sep='\t')
data_pdsp.info()

<class 'pandas.DataFrame'>
RangeIndex: 27715 entries, 0 to 27714
Columns: 640 entries, BindingDB Reactant_set_id to UniProt (TrEMBL) Alternative ID(s) of Target Chain 50
dtypes: float64(587), int64(6), str(47)
memory usage: 182.0 MB

C:\Users\alexl\AppData\Local\Temp\ipykernel_12564\117576025.py:1: DtypeWarning: Columns (0: UniProt (TrEMBL) Submitted Name of Target Chain 1, 1: UniProt (TrEMBL) Entry Name of Target Chain 1, 2: UniProt (TrEMBL) Primary ID of Target Chain 1, 3: UniProt (TrEMBL) Secondary ID(s) of Target Chain 1, 4: BindingDB Target Chain Sequence 2, 5: UniProt (SwissProt) Recommended Name of Target Chain 2, 6: UniProt (SwissProt) Entry Name of Target Chain 2, 7: UniProt (SwissProt) Primary ID of Target Chain 2, 8: UniProt (SwissProt) Secondary ID(s) of Target Chain 2, 9: BindingDB Target Chain Sequence 3, 10: UniProt (SwissProt) Recommended Name of Target Chain 3, 11: UniProt (SwissProt) Entry Name of Target Chain 3, 12: UniProt (SwissProt) Primary ID of Target Chain 3, 13: BindingDB Target Chain Sequence 4, 14: PDB ID(s) of Target Chain 4, 15: UniProt (SwissProt) Recommended Name of Target Chain 4, 16: UniProt (SwissProt) Entry Name of Target Chain 4, 17: UniProt (SwissProt) Primary ID of Target Chain 4, 18: UniProt (SwissProt) Secondary ID(s) of Target Chain 4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_pdsp = pd.read_csv(PDSP_DIR, sep='\t')

In [12]:
data_summry = pd.DataFrame({
    'Columns': data_pdsp.columns,
    'Data types': data_pdsp.dtypes,
    'Missing values': data_pdsp.isnull().sum(),
    'null%': data_pdsp.isnull().mean() * 100,
    'unique values': data_pdsp.nunique()
})

pd.set_option('display.max_rows', None)
display(data_summry)

,Columns,Data types,Missing values,null%,unique values
BindingDB Reactant_set_id,BindingDB Reactant_set_id,int64,0,0.000000,27715
Ligand SMILES,Ligand SMILES,str,0,0.000000,3303
Ligand InChI,Ligand InChI,str,0,0.000000,2990
Ligand InChI Key,Ligand InChI Key,str,0,0.000000,2990
BindingDB MonomerID,BindingDB MonomerID,int64,0,0.000000,3315
BindingDB Ligand Name,BindingDB Ligand Name,str,0,0.000000,3312
Target Name,Target Name,str,0,0.000000,400
Target Source Organism According to Curator or DataSource,Target Source Organism According to Curator or...,str,43,0.155151,41
Ki (nM),Ki (nM),str,0,0.000000,3972
IC50 (nM),IC50 (nM),float64,27715,100.000000,0
Kd (nM),Kd (nM),float64,27715,100.000000,0
EC50 (nM),EC50 (nM),float64,27715,100.000000,0
kon (M-1-s-1),kon (M-1-s-1),float64,27715,100.000000,0
koff (s-1),koff (s-1),float64,27715,100.000000,0
pH,pH,float64,27715,100.000000,0
Temp (C),Temp (C),float64,27715,100.000000,0
Curation/DataSource,Curation/DataSource,str,0,0.000000,1
Article DOI,Article DOI,str,8420,30.380660,493
BindingDB Entry DOI,BindingDB Entry DOI,str,0,0.000000,728
PMID,PMID,int64,0,0.000000,728
PubChem AID,PubChem AID,float64,27715,100.000000,0
Patent Number,Patent Number,float64,27715,100.000000,0
Authors,Authors,str,0,0.000000,722
Date of publication,Date of publication,str,0,0.000000,172
Date in BindingDB,Date in BindingDB,str,0,0.000000,91
Institution,Institution,str,0,0.000000,351
Link to Ligand in BindingDB,Link to Ligand in BindingDB,str,0,0.000000,3315
Link to Target in BindingDB,Link to Target in BindingDB,str,0,0.000000,751
Link to Ligand-Target Pair in BindingDB,Link to Ligand-Target Pair in BindingDB,str,0,0.000000,13447
Ligand HET ID in PDB,Ligand HET ID in PDB,str,21709,78.329424,295
PDB ID(s) for Ligand-Target Complex,PDB ID(s) for Ligand-Target Complex,str,22288,80.418546,277
PubChem CID,PubChem CID,int64,0,0.000000,3296
PubChem SID,PubChem SID,int64,0,0.000000,3315
ChEBI ID of Ligand,ChEBI ID of Ligand,float64,27715,100.000000,0
ChEMBL ID of Ligand,ChEMBL ID of Ligand,str,13526,48.803897,1079
DrugBank ID of Ligand,DrugBank ID of Ligand,str,20339,73.386253,364
IUPHAR_GRAC ID of Ligand,IUPHAR_GRAC ID of Ligand,float64,27715,100.000000,0
KEGG ID of Ligand,KEGG ID of Ligand,str,19058,68.764207,422
ZINC ID of Ligand,ZINC ID of Ligand,float64,27715,100.000000,0
Number of Protein Chains in Target (>1 implies a multichain complex),Number of Protein Chains in Target (>1 implies...,int64,0,0.000000,2
BindingDB Target Chain Sequence 1,BindingDB Target Chain Sequence 1,str,0,0.000000,747
PDB ID(s) of Target Chain 1,PDB ID(s) of Target Chain 1,str,12237,44.152986,426
UniProt (SwissProt) Recommended Name of Target Chain 1,UniProt (SwissProt) Recommended Name of Target...,str,1671,6.029226,354
UniProt (SwissProt) Entry Name of Target Chain 1,UniProt (SwissProt) Entry Name of Target Chain 1,str,1671,6.029226,633
UniProt (SwissProt) Primary ID of Target Chain 1,UniProt (SwissProt) Primary ID of Target Chain 1,str,1671,6.029226,630
UniProt (SwissProt) Secondary ID(s) of Target Chain 1,UniProt (SwissProt) Secondary ID(s) of Target ...,str,9378,33.837272,402
UniProt (SwissProt) Alternative ID(s) of Target Chain 1,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 1,UniProt (TrEMBL) Submitted Name of Target Chain 1,str,26125,94.263034,87
UniProt (TrEMBL) Entry Name of Target Chain 1,UniProt (TrEMBL) Entry Name of Target Chain 1,str,26125,94.263034,114
UniProt (TrEMBL) Primary ID of Target Chain 1,UniProt (TrEMBL) Primary ID of Target Chain 1,str,25364,91.517229,119
UniProt (TrEMBL) Secondary ID(s) of Target Chain 1,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,str,27602,99.592279,9
UniProt (TrEMBL) Alternative ID(s) of Target Chain 1,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 2,BindingDB Target Chain Sequence 2,str,27694,99.924229,1
PDB ID(s) of Target Chain 2,PDB ID(s) of Target Chain 2,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 2,UniProt (SwissProt) Recommended Name of Target...,str,27694,99.924229,1
UniProt (SwissProt) Entry Name of Target Chain 2,UniProt (SwissProt) Entry Name of Target Chain 2,str,27694,99.924229,1
UniProt (SwissProt) Primary ID of Target Chain 2,UniProt (SwissProt) Primary ID of Target Chain 2,str,27694,99.924229,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 2,UniProt (SwissProt) Secondary ID(s) of Target ...,str,27694,99.924229,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 2,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 2,UniProt (TrEMBL) Submitted Name of Target Chain 2,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 2,UniProt (TrEMBL) Entry Name of Target Chain 2,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 2,UniProt (TrEMBL) Primary ID of Target Chain 2,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 2,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 2,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 3,BindingDB Target Chain Sequence 3,str,27694,99.924229,1
PDB ID(s) of Target Chain 3,PDB ID(s) of Target Chain 3,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 3,UniProt (SwissProt) Recommended Name of Target...,str,27694,99.924229,1
UniProt (SwissProt) Entry Name of Target Chain 3,UniProt (SwissProt) Entry Name of Target Chain 3,str,27694,99.924229,1
UniProt (SwissProt) Primary ID of Target Chain 3,UniProt (SwissProt) Primary ID of Target Chain 3,str,27694,99.924229,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 3,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 3,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 3,UniProt (TrEMBL) Submitted Name of Target Chain 3,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 3,UniProt (TrEMBL) Entry Name of Target Chain 3,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 3,UniProt (TrEMBL) Primary ID of Target Chain 3,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 3,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 3,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 4,BindingDB Target Chain Sequence 4,str,27694,99.924229,1
PDB ID(s) of Target Chain 4,PDB ID(s) of Target Chain 4,str,27694,99.924229,2
UniProt (SwissProt) Recommended Name of Target Chain 4,UniProt (SwissProt) Recommended Name of Target...,str,27694,99.924229,1
UniProt (SwissProt) Entry Name of Target Chain 4,UniProt (SwissProt) Entry Name of Target Chain 4,str,27694,99.924229,1
UniProt (SwissProt) Primary ID of Target Chain 4,UniProt (SwissProt) Primary ID of Target Chain 4,str,27694,99.924229,1
UniProt (SwissProt) Secondary ID(s) of Target Chain 4,UniProt (SwissProt) Secondary ID(s) of Target ...,str,27694,99.924229,1
UniProt (SwissProt) Alternative ID(s) of Target Chain 4,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 4,UniProt (TrEMBL) Submitted Name of Target Chain 4,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 4,UniProt (TrEMBL) Entry Name of Target Chain 4,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 4,UniProt (TrEMBL) Primary ID of Target Chain 4,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 4,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 4,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 5,BindingDB Target Chain Sequence 5,float64,27715,100.000000,0
PDB ID(s) of Target Chain 5,PDB ID(s) of Target Chain 5,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 5,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 5,UniProt (SwissProt) Entry Name of Target Chain 5,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 5,UniProt (SwissProt) Primary ID of Target Chain 5,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 5,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 5,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 5,UniProt (TrEMBL) Submitted Name of Target Chain 5,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 5,UniProt (TrEMBL) Entry Name of Target Chain 5,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 5,UniProt (TrEMBL) Primary ID of Target Chain 5,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 5,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 5,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 6,BindingDB Target Chain Sequence 6,float64,27715,100.000000,0
PDB ID(s) of Target Chain 6,PDB ID(s) of Target Chain 6,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 6,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 6,UniProt (SwissProt) Entry Name of Target Chain 6,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 6,UniProt (SwissProt) Primary ID of Target Chain 6,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 6,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 6,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 6,UniProt (TrEMBL) Submitted Name of Target Chain 6,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 6,UniProt (TrEMBL) Entry Name of Target Chain 6,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 6,UniProt (TrEMBL) Primary ID of Target Chain 6,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 6,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 6,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 7,BindingDB Target Chain Sequence 7,float64,27715,100.000000,0
PDB ID(s) of Target Chain 7,PDB ID(s) of Target Chain 7,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 7,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 7,UniProt (SwissProt) Entry Name of Target Chain 7,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 7,UniProt (SwissProt) Primary ID of Target Chain 7,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 7,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 7,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 7,UniProt (TrEMBL) Submitted Name of Target Chain 7,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 7,UniProt (TrEMBL) Entry Name of Target Chain 7,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 7,UniProt (TrEMBL) Primary ID of Target Chain 7,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 7,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 7,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 8,BindingDB Target Chain Sequence 8,float64,27715,100.000000,0
PDB ID(s) of Target Chain 8,PDB ID(s) of Target Chain 8,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 8,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 8,UniProt (SwissProt) Entry Name of Target Chain 8,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 8,UniProt (SwissProt) Primary ID of Target Chain 8,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 8,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 8,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 8,UniProt (TrEMBL) Submitted Name of Target Chain 8,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 8,UniProt (TrEMBL) Entry Name of Target Chain 8,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 8,UniProt (TrEMBL) Primary ID of Target Chain 8,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 8,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 8,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 9,BindingDB Target Chain Sequence 9,float64,27715,100.000000,0
PDB ID(s) of Target Chain 9,PDB ID(s) of Target Chain 9,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 9,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 9,UniProt (SwissProt) Entry Name of Target Chain 9,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 9,UniProt (SwissProt) Primary ID of Target Chain 9,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 9,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 9,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 9,UniProt (TrEMBL) Submitted Name of Target Chain 9,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 9,UniProt (TrEMBL) Entry Name of Target Chain 9,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 9,UniProt (TrEMBL) Primary ID of Target Chain 9,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 9,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 9,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 10,BindingDB Target Chain Sequence 10,float64,27715,100.000000,0
PDB ID(s) of Target Chain 10,PDB ID(s) of Target Chain 10,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 10,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 10,UniProt (SwissProt) Entry Name of Target Chain 10,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 10,UniProt (SwissProt) Primary ID of Target Chain 10,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 10,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 10,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 10,UniProt (TrEMBL) Submitted Name of Target Chai...,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 10,UniProt (TrEMBL) Entry Name of Target Chain 10,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 10,UniProt (TrEMBL) Primary ID of Target Chain 10,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 10,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 10,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 11,BindingDB Target Chain Sequence 11,float64,27715,100.000000,0
PDB ID(s) of Target Chain 11,PDB ID(s) of Target Chain 11,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 11,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 11,UniProt (SwissProt) Entry Name of Target Chain 11,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 11,UniProt (SwissProt) Primary ID of Target Chain 11,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 11,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 11,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 11,UniProt (TrEMBL) Submitted Name of Target Chai...,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 11,UniProt (TrEMBL) Entry Name of Target Chain 11,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 11,UniProt (TrEMBL) Primary ID of Target Chain 11,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 11,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 11,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 12,BindingDB Target Chain Sequence 12,float64,27715,100.000000,0
PDB ID(s) of Target Chain 12,PDB ID(s) of Target Chain 12,float64,27715,100.000000,0
UniProt (SwissProt) Recommended Name of Target Chain 12,UniProt (SwissProt) Recommended Name of Target...,float64,27715,100.000000,0
UniProt (SwissProt) Entry Name of Target Chain 12,UniProt (SwissProt) Entry Name of Target Chain 12,float64,27715,100.000000,0
UniProt (SwissProt) Primary ID of Target Chain 12,UniProt (SwissProt) Primary ID of Target Chain 12,float64,27715,100.000000,0
UniProt (SwissProt) Secondary ID(s) of Target Chain 12,UniProt (SwissProt) Secondary ID(s) of Target ...,float64,27715,100.000000,0
UniProt (SwissProt) Alternative ID(s) of Target Chain 12,UniProt (SwissProt) Alternative ID(s) of Targe...,float64,27715,100.000000,0
UniProt (TrEMBL) Submitted Name of Target Chain 12,UniProt (TrEMBL) Submitted Name of Target Chai...,float64,27715,100.000000,0
UniProt (TrEMBL) Entry Name of Target Chain 12,UniProt (TrEMBL) Entry Name of Target Chain 12,float64,27715,100.000000,0
UniProt (TrEMBL) Primary ID of Target Chain 12,UniProt (TrEMBL) Primary ID of Target Chain 12,float64,27715,100.000000,0
UniProt (TrEMBL) Secondary ID(s) of Target Chain 12,UniProt (TrEMBL) Secondary ID(s) of Target Cha...,float64,27715,100.000000,0
UniProt (TrEMBL) Alternative ID(s) of Target Chain 12,UniProt (TrEMBL) Alternative ID(s) of Target C...,float64,27715,100.000000,0
BindingDB Target Chain Sequence 13,BindingDB Target Chain Sequence 13,float64,27715,100.000000,0
PDB ID(s) of Target Chain 13,PDB ID(s) of Target Chain 13,float64,27715,100.000000,0